# Generated by Django 5.0.6 on 2024-06-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
    ]
